ci: upload playwright test report (#3877)
* chore: upload playwright test report in ci

* chore: use actions version commit sha

* feat: add gha workflow to update visual test snapshots

* chore: fix permissions for pr comment

* chore: find the playwright test report path

* chore: force output

* chore: test-results path

* chore: find the playwright diff files

* chore: add pr trigger

* chore: intentional snapshot diff

* chore: update snapshot names

* chore: add linux snapshots with diff

* chore: dont test mobile safari

* chore: only upload diffs on failing test

* chore: update snapshot failure message

* chore: do not post comment when not PR

* chore: update trigger

* chore: update snapshot

* chore: run on safari mobile

* chore: get event name

* chore: only comment on pull request

diff --git a/.github/workflows/test-cdn-jsdelivr.yml b/.github/workflows/test-cdn-jsdelivr.yml
--- a/.github/workflows/test-cdn-jsdelivr.yml
+++ b/.github/workflows/test-cdn-jsdelivr.yml
@@ -4,7 +4,7 @@ on:
   schedule:
     # every hour
     - cron: '0 * * * *'
-  push:
+  pull_request:
     paths:
       - 'playwright/tests/**'
       - 'examples/cdn-api-reference/**'
@@ -12,11 +12,13 @@ on:
 
 jobs:
   test:
-    runs-on: macos-latest
+    runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [20]
-
+    permissions:
+      contents: write
+      pull-requests: write
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
@@ -53,4 +55,29 @@ jobs:
       - name: Start HTML server
         run: pnpm --filter @scalar-examples/cdn-api-reference dev &
       - name: Run E2E tests (jsdelivr)
-        run: CI=1 pnpm test:e2e:jsdelivr
+        run: |
+          CI=1 pnpm test:e2e:jsdelivr | tee output.log
+          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
+            echo "Playwright tests failed due to a snapshot issue."
+            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
+            exit 1
+          elif grep -q "failed" output.log; then
+            echo "Playwright tests failed due to a non-snapshot issue."
+            exit 1
+          fi
+      - uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
+        id: artifact-upload
+        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
+        with:
+          name: playwright-report
+          path: ./playwright/test-results/
+          retention-days: 7
+      - name: Comment on PR with report link
+        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
+        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' && github.event_name == 'pull_request'}}
+        with:
+          message: |
+            ### Playwright visual snapshot differences were detected.
+            View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
+            Inspect the changes and commit the updated snapshots if they are satisfactory.
+            If a **snapshot-diff.png** is not provided, the snapshots are different sizes.
